### ISSUE TITLE
mxj/x2j is advertived as a migration path from x2J however it is missing functions like ByteDocToMap

### ISSUE THREAD

**Issue by nim-nim** [clbanning/mxj#44]
Existing x2j users like
https://github.com/hudl/fargo/blob/master/metadata.go#L50

expect x2j.ByteDocToMap to exist

```
    // XML: wrap in a BS xml tag so all metadata tags are pulled
    fullDoc := append(append([]byte("<d>"), im.Raw...), []byte("</d>")...)
    parsedDoc, err := x2j.ByteDocToMap(fullDoc, true)
    if err != nil {
      log.Errorf("Error unmarshalling: %s", err.Error())
      return fmt.Errorf("error unmarshalling: %s", err.Error())
    }
    im.parsed = parsedDoc["d"].(map[string]interface{})
```

**Comment by clbanning** [comment]
Well, "github.com/clbanning/x2j" is still out there.  (Though not as performant as "mxj" when unmarshaling XML.)

The "x2j" wrapper functions in "github.com/clbanning/mxj/x2j" brought over just some basic functionality of "x2j" package under a new naming convention rather than replicating everything that was in the "mxj" package itself.

My recommendation would be to import "github.com/clbanning/mxj" instead and change <code>x2j.ByteDocToMap(fullDoc, true)</code> to <code>mxj.NewMapXml(fullDoc, true)</code>.  If you vendor the 3rd party packages you're using, that shouldn't be a problem.

**Comment by clbanning** [comment]
Though not as performant when unmarshaling XML, "github.com/clbanning/x2j" is still available.

The "github.com/clbanning/mxj/x2j" wrapper package only includes some high-level functions that were in the original "x2j" package and adopts a naming convention more consistent with the "mxj" package itself.  "x2j" functions that are in "mxj" are not replicated.

Assuming that you've vendored the "fargo" repo, I'd recommend that you change the import on line 9 of the source file to "github.com/clbanning/mxj" and then change the call <code>x2j.ByteDocToMap(fullDoc, true)</code> to <code>mxj.NewMapXml(fullDoc, true)</code>.

**Comment by nim-nim** [comment]
Thanks a lot for the advice, I wanted to avoid patching  as much as possible, but looks I will have to do it anyway

If you o not want to expose old function names, could you document somewhere how to port from them to the new ones? There are so many naming changes porting is not obvious when you don't know the codebase. (even more a PITA when you don't know the x2J/mxj codebase and the x2j import is in someone else's code).

**Comment by clbanning** [comment]
Good point.  Poor documentation, which I hadn't looked at in a long, long while.  

I've added" mxj/x2j-wrapper" sub-package as a near literal port of the old "x2j" package.  (Doesn't include old decoder logic for intermediate "tree" representation, since it uses "mxj" functions that decode XML directly to a <code>map[string]interface{}</code> value.)

**Comment by nim-nim** [comment]
Wondeful!

I hope that will finally wean projects out of x2j!
