### ISSUE TITLE
XML unexpected EOF

### ISSUE THREAD

**Issue by kpacha** [clbanning/mxj#63]
When using the http.Response.Body as a reader to pass to `NewMapXMLReader`, it fails to parse XML responses not ending with a line break.

Here a test showing the error: https://play.golang.org/p/ob6DnGUwtLx

I was able to fix it in my project using this wrapper over the `http.Response.Body`:

```
type xmlReader struct {
	r io.Reader
}

func (x xmlReader) Read(p []byte) (n int, err error) {
	n, err = x.r.Read(p)

	if err != io.EOF {
		return n, err
	}

	if len(p) == n {
		return n, nil
	}

	p[n] = ([]byte("\n"))[0]
	return n + 1, err
}
```

It's not pretty but it worked https://play.golang.org/p/bITvPyFHuZ6

Don't you think this should be managed by the mxj lib itself?

**Comment by clbanning** [comment]
I wish it could be managed.  The error is coming from `encoding/xml` package in standard library, see line 290: https://golang.org/src/encoding/xml/xml.go?s=8197:8237#L290

**Comment by clbanning** [comment]
The error is coming from `encoding/xml`; see line 290 in https://golang.org/src/encoding/xml/xml.go?s=8197:8237#L269.

My code does not directly manipulate the `io.Reader` being passed to `xml.NewDecode(r io.Reader)`.  I've found a couple of workarounds for your test case:

- like you, add a character to the end of the `http.Response.Body` - even just a space character, `' '` will do - https://play.golang.org/p/_bcZ4luW1ij.

- reading the `http.Response.Body` into a `bytes.Buffer` and passing the buffer as a `io.Reader` works as well - https://play.golang.org/p/3FcrypTrS3y

Unfortunately neither can be implemented, since the `io.Reader` may be a data stream, such as, `*io.File`. 

There must be a logic error somewhere in the `clbanning/mxj` package, however, since passing the `http.Response.Body` directly to `xml.NewDecoder` and then parsing it with `*Decoder.Token` is parsing it correctly - https://play.golang.org/p/09dP4DCS3wq.

This is the first time since 7/2012 when the parser logic was first used in `github.com/clbanning/x2j` that this has come up.  I'm open for suggestions and will spend some more time trying to identify what's going on after I upgrade from go v1.11.4 to tip.

**Comment by clbanning** [comment]
Fixed on tip.  Thanks.
