### ISSUE TITLE
Integration with Google oss-fuzz fuzzing service

### ISSUE THREAD

**Issue by manunio** [clbanning/mxj#99]
Hi, I would like to help integrate this project into Google [oss-fuzz](https://github.com/google/oss-fuzz).

- As an initial step for integration I have created this PR: https://github.com/google/oss-fuzz/pull/8155,  it contains necessary logic from an OSS-Fuzz perspective to integrate mxj. This includes developing initial fuzzers as well as integrating into OSS-Fuzz.

- Essentially, OSS-Fuzz is a free service run by Google that performs continuous fuzzing of important open source projects.

- **If you would like to integrate, could I please have an email(s)**, it must be associated with a Google account like gmail ([why?](https://google.github.io/oss-fuzz/faq/#why-do-you-require-a-google-account-for-authentication)). by doing that, the provided email(s) will get access to the data produced by OSS-Fuzz, such as bug reports, coverage reports and more stats.

- Notice the email(s) affiliated with the project will be public in the OSS-Fuzz repo, as they will be part of a configuration file.

**Comment by clbanning** [comment]
I would like to have a little more rationale for integrating with oss-fuzz.  I assume that you want to fuzz this package with various invalid XML objects.  But since `NewMapXml` just uses the stdlib `xml.Decoder.Token` method you're really just fuzzing the Go stdlib XML parser.  Why not just integrate the stdlib `encode/xml` package with oss-fuzz?
